apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-frontend
  namespace: {{ .Values.StudentStoreFrontend.studentFeDeploy.namespace }}
  labels:
    type: frontend
spec:
  replicas: {{ .Values.StudentStoreFrontend.studentFeDeploy.replicasCount }}
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
        - name: mywebapp
          image: 8072388539/datastore-frontend:{{ .Values.StudentStoreFrontend.studentFeDeploy.imageTag }}
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: datastore-fe-cm
                  key: backendEndpoint
          resources:
{{ toYaml .Values.StudentStoreFrontend.studentFeDeploy.containerResources | nindent 12 }}
          livenessProbe:
{{ toYaml .Values.StudentStoreFrontend.studentFeDeploy.livenessProbe | nindent 12 }}
          readinessProbe:
{{ toYaml .Values.StudentStoreFrontend.studentFeDeploy.readinessProbe | nindent 12 }}
          startupProbe:
{{ toYaml .Values.StudentStoreFrontend.studentFeDeploy.startupProbe | nindent 12 }}
