apiVersion: v1
kind: ConfigMap
namespace: {{ .Values.StudenStoreFrontend.studentFeDeploy.namespace }}
metadata:
  name: datastore-fe-cm
data:
  backendEndpoint: {{ .Values.studentFeConfigMap.backendEndpoint }}

