apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: {{ .Values.StudentStoreBackend.StudentDeploy.namespace }}
data:
  mysqlHost: {{ .Values.StudentStoreBackend.StudentCm.mysqlHost | quote }}
  name: {{ .Values.StudentStoreBackend.StudentCm.name | quote }}
