apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-backend
  namespace: {{ .Values.StudentStoreBackend.StudentDeploy.namespace }}
  labels:
    type: datastore-backend
spec:
  replicas: {{ .Values.StudentStoreBackend.StudentDeploy.replicaCount }}
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: datastore-backend
      labels:
        type: backend
    spec:
      containers:
        - name: datastore-backend
          image: 8072388539/datastore:{{ .Values.StudentStoreBackend.StudentDeploy.image }}
          ports:
            - containerPort: 8084
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: mysqlHost
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: name
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datastore-be-secret
                  key: mysqlPassword
          resources:
{{ toYaml .Values.StudentStoreBackend.StudentDeploy.resources | nindent 12 }}
          livenessProbe:
{{ toYaml .Values.StudentStoreBackend.StudentDeploy.livenessProbe | nindent 12 }}
          readinessProbe:
{{ toYaml .Values.StudentStoreBackend.StudentDeploy.readinessProbe | nindent 12 }}
          startupProbe:
{{ toYaml .Values.StudentStoreBackend.StudentDeploy.startupProbe | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: datastore-backend-svc
  namespace: {{ .Values.StudentStoreBackend.StudentSvc.namespace }}
spec:
  ports:
    - port: {{ .Values.StudentStoreBackend.StudentSvc.svcPort }}
      targetPort: 8084
  selector:
    type: backend
