apiVersion: v1
kind: Secret
metadata:
  name: datastore-be-secret
  namespace: {{ .Values.StudentStoreBackend.StudentDeploy.namespace }}
type: Opaque
data:
  mysqlPassword: {{ .Values.StudentStoreBackend.StudentSecret.mysqlPassword | b64enc }}
